### ISSUE TITLE
一个格式的小建议

### ISSUE THREAD

**Issue by taseikyo** [kelthuzadx/Cpp17TheCompleteGuideChinese#1]
最近我也在啃《C++17 - The Complete Guide》这本书，奈何英文原版还是太难啃了 2333
于是找到这个：https://github.com/JoshuaShuo77/Cpp17
但是他缺了第七章 *Chapter 7 New Attributes and Attribute Features*
然后就找到你的这版，正好正在翻译过程中，所以有个格式的小建议，希望后面章节能中英文之间加个空格（强迫症 :p），所谓的“盘古之白”，可以使阅读体验更佳 :D

最后，再次感谢翻译！

**Comment by kelthuzadx** [comment]
是这个意思吗：

This is what std::variant did   ->  这就是[空格]std::variant[空格]做的事情

**Comment by taseikyo** [comment]
对 就是个意思 :p
